if(CMAKE_C_COMPILER_ID MATCHES "ARMClang")
	add_custom_command(TARGET ${EXECUTABLE_NAME}
		POST_BUILD
		COMMAND ${CMAKE_FROMELF} --i32 $<TARGET_FILE:${EXECUTABLE_NAME}> --output $<TARGET_FILE_DIR:${EXECUTABLE_NAME}>/${EXECUTABLE_NAME}.hex
		COMMAND ${CMAKE_FROMELF} --bin $<TARGET_FILE:${EXECUTABLE_NAME}> --output $<TARGET_FILE_DIR:${EXECUTABLE_NAME}>/${EXECUTABLE_NAME}.bin
		COMMAND ${CMAKE_FROMELF} --text -z $<TARGET_FILE:${EXECUTABLE_NAME}>
	)

elseif(CMAKE_C_COMPILER_ID MATCHES "GNU")
	add_custom_command(TARGET ${EXECUTABLE_NAME}
		POST_BUILD
		COMMAND ${CMAKE_OBJDUMP} -h -S $<TARGET_FILE:${EXECUTABLE_NAME}> > $<TARGET_FILE_DIR:${EXECUTABLE_NAME}>/${EXECUTABLE_NAME}.list
		COMMAND ${CMAKE_OBJCOPY} -O ihex $<TARGET_FILE:${EXECUTABLE_NAME}> $<TARGET_FILE_DIR:${EXECUTABLE_NAME}>/${EXECUTABLE_NAME}.hex
		COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${EXECUTABLE_NAME}> $<TARGET_FILE_DIR:${EXECUTABLE_NAME}>/${EXECUTABLE_NAME}.bin
	)
endif()
